# December 20, 2023

https://adventofcode.com/2023/day/20

In [52]:
from queue import PriorityQueue

In [1]:
text = f'''...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
...........'''

test_text = text.split("\n")

In [73]:
fn = "data/21.txt"
with open(fn, "r") as file:
    text = file.readlines()

puzz_text = [x.strip() for x in text]

In [8]:
def borderize( text ):
    # add a rock boundary to the garden to simplify later algos
    w = len(text[0]) + 2
    
    new_text = ["#" * w]
    for line in text:
        new_text.append( "#" + line + "#" )
    new_text.append( "#"*w )
    return new_text
    



In [53]:
class Garden:
    def __init__(self, text):
        text = borderize(text)

        self.width = len(text[0])
        self.height = len(text)
        self.adj = {}
        self.start = None

        for row, line in enumerate(text):
            for col, char in enumerate(line):
                if char == "#":
                    continue
                else:
                    # get non # neighbors
                    code = self.encode(row, col)
                    row_try = [row-1, row, row, row+1]
                    col_try = [col, col-1, col+1, col]
                    self.adj[code] = [ self.encode(r,c) for r,c in zip(row_try, col_try) if text[r][c] != "#" ]

                    if char == "S":
                        self.start = code

    def encode(self, row, col):
        return row*self.width + col
    
    def decode(self, code):
        row = int(code/self.width)
        col = code % self.width
        return row, col
    
    def create_dist_map( self ):
        self.dist = {self.start:0}
        explore = PriorityQueue()
        explore.put( (0, self.start) )

        while not explore.empty() > 0:
            dist, code = explore.get()
            nbrs = self.adj[code]

            for nbr in nbrs:
                if nbr in self.dist.keys():
                    continue
                    # check if we should update the distance
                    if self.dist[nbr] > self.dist[code] + 1:
                        self.dist[nbr] = self.dist[code] + 1
                else:
                    # new location to add to our distance map!
                    dist_to_nbr = dist + 1
                    self.dist[nbr] = dist_to_nbr
                    explore.put( (dist_to_nbr, nbr) )


             



### Part 1

In [54]:
test = Garden(test_text)

In [47]:
test.adj

{14: [15, 27],
 15: [14, 16, 28],
 16: [15, 17, 29],
 17: [16, 18, 30],
 18: [17, 19, 31],
 19: [18, 20],
 20: [19, 21],
 21: [20, 22],
 22: [21, 23, 35],
 23: [22, 24],
 24: [23, 37],
 27: [14, 28, 40],
 28: [15, 27, 29],
 29: [16, 28, 30],
 30: [17, 29, 31],
 31: [18, 30, 44],
 35: [22, 48],
 37: [24, 50],
 40: [27, 53],
 44: [31],
 47: [48, 60],
 48: [35, 47],
 50: [37, 63],
 53: [40, 54, 66],
 54: [53, 67],
 56: [69],
 58: [59, 71],
 59: [58, 60],
 60: [47, 59, 73],
 62: [63, 75],
 63: [50, 62, 76],
 66: [53, 67, 79],
 67: [54, 66, 68],
 68: [67, 69],
 69: [56, 68, 82],
 71: [58, 84],
 73: [60, 74],
 74: [73, 75],
 75: [62, 74, 76],
 76: [63, 75, 89],
 79: [66, 92],
 82: [69, 83, 95],
 83: [82, 84, 96],
 84: [71, 83],
 89: [76, 102],
 92: [79, 105],
 95: [82, 96, 108],
 96: [83, 95, 109],
 98: [99, 111],
 99: [98, 100],
 100: [99],
 102: [89, 115],
 105: [92, 106, 118],
 106: [105, 107],
 107: [106, 108],
 108: [95, 107, 109, 121],
 109: [96, 108, 110],
 110: [109, 111, 123],
 111:

In [48]:
test.start

84

In [49]:
test.decode(84)

(6, 6)

In [55]:
test.create_dist_map()

In [56]:
test.dist

{84: 0,
 71: 1,
 83: 1,
 58: 2,
 82: 2,
 96: 2,
 59: 3,
 69: 3,
 95: 3,
 109: 3,
 60: 4,
 56: 4,
 68: 4,
 108: 4,
 110: 4,
 47: 5,
 73: 5,
 67: 5,
 107: 5,
 121: 5,
 111: 5,
 123: 5,
 48: 6,
 54: 6,
 66: 6,
 74: 6,
 106: 6,
 98: 6,
 134: 6,
 35: 7,
 53: 7,
 79: 7,
 75: 7,
 99: 7,
 105: 7,
 135: 7,
 147: 7,
 22: 8,
 40: 8,
 62: 8,
 76: 8,
 92: 8,
 100: 8,
 118: 8,
 148: 8,
 146: 8,
 21: 9,
 23: 9,
 27: 9,
 63: 9,
 89: 9,
 131: 9,
 145: 9,
 149: 9,
 20: 10,
 24: 10,
 14: 10,
 28: 10,
 50: 10,
 102: 10,
 144: 10,
 150: 10,
 15: 11,
 19: 11,
 37: 11,
 29: 11,
 115: 11,
 151: 11,
 16: 12,
 18: 12,
 30: 12,
 114: 12,
 128: 12,
 138: 12,
 152: 12,
 17: 13,
 31: 13,
 141: 13,
 153: 13,
 44: 14,
 154: 14}

In [64]:
cool = []
steps = 6
for k,v in test.dist.items():
    if v <= steps and v % 2 == 0:
        cool.append(k)

len(cool), cool


(16, [84, 58, 82, 96, 60, 56, 68, 108, 110, 48, 54, 66, 74, 106, 98, 134])

In [79]:
def part1( text, steps ):
    puzz = Garden(text)
    puzz.create_dist_map()

    cool = []
    parity = steps % 2

    for k,v in puzz.dist.items():
        if v <= steps and v % 2 == parity:
            cool.append(k)

    return len(cool)


In [80]:
part1( test_text, 6 )

16

In [81]:
part1( puzz_text, 1 )

4

In [82]:
part1( puzz_text, 64 )

3594

### Part 2

In [166]:
class Garden2:
    def __init__(self, text):
        '''Assumes open path around the outside, through the middle in both directions, with S in the center'''
        text = borderize(text)

        self.width = len(text[0])
        self.height = len(text)
        self.adj = {}
        self.start = None

        # create adjacency matrix
        for row, line in enumerate(text):
            for col, char in enumerate(line):
                if char == "#":
                    continue
                else:
                    # get non # neighbors
                    code = self.encode(row, col)
                    row_try = [row-1, row, row, row+1]
                    col_try = [col, col-1, col+1, col]
                    self.adj[code] = [ self.encode(r,c) for r,c in zip(row_try, col_try) if text[r][c] != "#" ]

                    if char == "S":
                        self.start = code

        # create distance maps from each possible start: center or an edge's mid or end
        self.__create_all_dist_maps__()
        self.radius = (self.height-3)/2 # distance from Start S to an edge following the open straight path

    def encode(self, row, col):
        return row*self.width + col
    
    def decode(self, code):
        row = int(code/self.width)
        col = code % self.width
        return row, col
    
    def __create_all_dist_maps__( self ):
        self.dist_maps = {}
        
        rlow =  clow = 1
        rmid, cmid = self.decode(self.start)
        rhi, chi = self.height - 2, self.width - 2
        rstart = [rlow, rlow, rlow, rmid, rmid, rmid, rhi , rhi , rhi]
        cstart = [clow, cmid, chi , clow, cmid, chi , clow, cmid, chi]

        for r, c in zip(rstart, cstart):
            code = self.encode(r,c)
            self.dist_maps[code] = self.create_dist_map( start = code )

    
    def create_dist_map( self, start=None ):
        if start is None:
            start = self.start

        dist_to_all = {start:0}
        explore = PriorityQueue()
        explore.put( (0, start) )

        while not explore.empty() > 0:
            dist, code = explore.get()
            nbrs = self.adj[code]

            for nbr in nbrs:
                if nbr not in dist_to_all.keys():
                    dist_to_nbr = dist + 1
                    dist_to_all[nbr] = dist_to_nbr
                    explore.put( (dist_to_nbr, nbr) )

        return dist_to_all


             



### Notes

Each replication of the main map is a "card".  
Each space on a card is a "tile". (I probably should've called it a space, but here we are.)

(26501365-65)/131 = 202300.

It takes 65 steps from S to edge, 131 steps from edge to the same edge on the next card.  

The reachable cards form a diamond with  
|R| + |C| <= 202300,  
where R<0 indicates cards above the start and C<- indicates cards left of the start

In [167]:
puzz = Garden2(puzz_text)

In [168]:
puzz.dist_maps.keys()

dict_keys([134, 199, 264, 8779, 8844, 8909, 17424, 17489, 17554])

In [169]:
puzz.start

8844

In [170]:
max( puzz.dist_maps[puzz.start].values() )

130

Another clue! With 130 steps, the elf can get from the center of the card to any tile on that card.  
For cards on the interior of the diamond, she can reach the center tile with 65+131 steps to spare.   
This means the tiles thereon are limited only by parity.

**Solve the interior cards first**  
On the interior:
* For each odd card, the elf can reach any odd tile (because she has to take an odd number of steps)
* For each even card, the parity of tiles flips, so she can reach any even tile

In [201]:
# calculate the number of "odd" cards:
def count_interior_cards( N ):
    # For each quadrant of the diamond it looks like this for N=6
    # the x's are the center line, which we'll handle separately to avoid double-counting
    # We assume N is even as it is in this problem
    
    # For this puzzle, N=2023, but here's a schematic for N=6
    # The x's are even cards, but we have to handle them separately, since the elf can't reach all tiles therein
    # The C is the exact center, which is an odd card

    #       X
    #      XEX
    #     XEOEX
    #    XEOEOEX
    #   XEOEOEOEX
    #  XEOEOEOEOEX
    # XEOEOECEOEOEX
    #  XEOEOEOEOEX
    #   XEOEOEOEX
    #    XEOEOEX
    #     XEOEX
    #      XEX
    #       X

    ### ON THE INTERIOR ###
    # the number of odd cards is
    # 1 + 4 * ( 2 + 4 + 6 + ... + N-2 )
    # which is the same as
    # 1 + 8 * ( 1+2+3+ ... + (N-2)/2 )
    
    max = (N-2)/2
    odd_interior_cards = 1 + 8 * (max*(max+1))/2 

    # the total number of cards is
    # 1 + 4 * (1+2+3+ ... N-1)
    interior_cards = 1 + 4 * (N-1)*N/2
    even_interior_cards = interior_cards - odd_interior_cards

    # per side, not total, because we'll approach each edge from a different starting tile
    #edge_cards = (N-2)
    #corner_cards = 1

    return odd_interior_cards, even_interior_cards#, edge_cards, corner_cards

In [221]:
101149*101150/2*8 + 1

40924885401.0

In [222]:
202300*202299/2*4+1

81850175401.0

In [223]:
odd_cards + even_cards

81850175401.0

In [205]:
count_interior_cards(6)

(25.0, 36.0)

In [206]:
odd_cards, even_cards = count_interior_cards(202300)
odd_cards, even_cards

(40924885401.0, 40925290000.0)

In [224]:
even_cards - odd_cards

404599.0

In [225]:
# Now find the even/odd garden tiles (this excludes rock tiles)
# It also excludes a handful of tiles that are unreachable because they are surrounded by rocks
from_center = puzz.dist_maps[puzz.start]
odd_tiles = len([k for k,v in from_center.items() if v % 2 ==1])
even_tiles = len([k for k,v in from_center.items() if v % 2 ==0])

odd_tiles, even_tiles

(7401, 7388)

In [208]:
part2 = {'interior': odd_cards*odd_tiles + even_cards*even_tiles}
part2

{'interior': 605241119372801.0}

**Time to solve the exterior**

For the compass points (straight N/E/W/S), the elf enters on the middle of the edge and has 130 steps left  
So for each of the middle edges we just add up how many spaces are reachable in 130 steps  
(It's not 131 steps, because we assume she took the first step from edge of interior card onto this exterior card)

For the other exteriors, the elf headed NE for 202300-2 of them, meaning the elf enters from the SW corner.  
In this case she has 131+65-1=195 steps remaining.

Since we're counting steps from the first tile she enters that card, we don't care about the parity of the card.


In [226]:
puzz.dist_maps.keys()

dict_keys([134, 199, 264, 8779, 8844, 8909, 17424, 17489, 17554])

In [227]:
mids = [199,8779,8909,17489]
corners = [134,264,17424,17554]

In [211]:
def reachable_in_n( dist_map, nsteps):
    parity = nsteps % 2
    return len( [k for k,v in dist_map.items() if v <= nsteps and v%2 == parity] )

In [212]:
compass = [reachable_in_n( puzz.dist_maps[cd], 130 ) for cd in mids]
compass

[5593, 5569, 5587, 5563]

In [213]:
part2['compass'] = sum(compass)

In [214]:
edge = [reachable_in_n( puzz.dist_maps[cd], 195) for cd in corners]
edge

[6498, 6496, 6472, 6492]

In [215]:
part2['edge'] = 202298 * sum(edge)

In [216]:

part2

{'interior': 605241119372801.0, 'compass': 22312, 'edge': 5251251484}

In [217]:
sum( [v for v in part2.values()] )

605246370646597.0

### Incorrect guesses
605246375906384.0 is too low  
mistake 1 is that the last interior card is an even card, not an odd card.  
mistake 2 is that the elf can reach additional cards from the "exterior" cards by heading straight there.
mistake 3 is that there are N-1 "exterior cards" excluding the compass points, rather than N-2

In [236]:
# function now fixed
odd_cards, even_cards = count_interior_cards(202300)
print( odd_cards, even_cards )

# didn't change
from_center = puzz.dist_maps[puzz.start]
odd_tiles = len([k for k,v in from_center.items() if v % 2 ==1])
even_tiles = len([k for k,v in from_center.items() if v % 2 ==0])

print( odd_tiles, even_tiles )



40924885401.0 40925290000.0
7401 7388


In [237]:
compass = [reachable_in_n( puzz.dist_maps[cd], 130 ) for cd in mids]
compass

[5593, 5569, 5587, 5563]

In [239]:
edge1 = [reachable_in_n( puzz.dist_maps[cd], 195) for cd in corners]
edge2 = [reachable_in_n( puzz.dist_maps[cd], 64) for cd in corners]
edge1, edge2 

([6498, 6496, 6472, 6492], [949, 938, 948, 959])

In [240]:
# total tiles:
N = 202300
part2 = (
    [odd_tiles * odd_cards, # odd tiles on all odd cards
     even_tiles * even_cards, # even tiles on all even cards
     sum(compass), # reachable on the last card in each compass direction
     (N-1)*sum(edge1), # reachable on "exterior" cards not in each compass direction
     N*sum(edge2) # spill over from exterior cards that can hit a few tiles on the next card
    ]
)

In [241]:
sum(part2), part2

(605247138198755.0,
 [302885076852801.0, 302356042520000.0, 22312, 5251277442, 767526200])

In [243]:
605247138198755.0 - 605246375906384

762292371.0


# Scratch

In [230]:
for k,v in puzz.dist_maps.items():
    print(k, max(v.values()))

134 260
199 195
264 260
8779 195
8844 130
8909 195
17424 260
17489 195
17554 260


In [231]:
# going straight in a cardinal direction
26501365 - (202299*131+66)

130

In [233]:
# going to the corner of an "exterior" tile not on the compass point
26501365 - (202298*131+66+66)

195

In [238]:
# gong to an exterior tile, then shortest path to the next furthest tile
# all three should be the same
26501365 - (202298*131+66+66) - 131, 130-66, 195-131

(64, 64, 64)